// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uphlcyadobbdzdwbyovz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwaGxjeWFkb2JiZHpkd2J5b3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MTE2MTYsImV4cCI6MjA4NjA4NzYxNn0.R3S9kIeY_khxwmZ5x1ihEz3u9H31bmEoWMFKGRD8uXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
